create table supply (
  id integer generated by default as identity,
  name varchar(255) not null,
  points integer,

  primary key (id)
);

insert into
  supply
  (name, points)
values
  ('Fiji Water', 14),
  ('Campbell Soup', 12),
  ('First Aid Pouch', 10),
  ('AK47', 8);