create table supply_bag (
    id int generated by default as identity,
    quantity int,
    supply_id int not null,
    bag_id int not null,

    primary key (id),
    foreign key (supply_id) references supply (id),
    foreign key (bag_id) references bag (id)
);