create table survivor (
    id int generated by default as identity,
    name varchar(150) not null,
    age int not null,
    gender varchar(10) not null,
    lat decimal(10,8),
    lng decimal(11,8),
    infected boolean default false,
    bag_id int,

    primary key (id),
    foreign key (bag_id) references bag(id)
);