create table infection_report (
    id int generated by default as identity,
    target_survivor_id int not null,
    reporter_survivor_id int not null,

    primary key (id),
    foreign key (target_survivor_id) references survivor (id),
    foreign key (reporter_survivor_id) references survivor (id)
);